### ISSUE TITLE
Unknown BroadLink device

### ISSUE THREAD

**Issue by willhains** [lprhodes/broadlinkjs-rm#11]
```
[Info] We've discovered an unknown Broadlink device. This likely won't cause any issues.

Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "27c2". The device is connected to your network with the IP address "192.168.3.52".
```

On the underside of the device, it says:
![img_0059](https://user-images.githubusercontent.com/1386812/48486501-1106de00-e85f-11e8-8a50-7462902308c2.jpg)

**Comment by KaloNikolov** [comment]
Hi as I also just bought this item and wanted to control it from a local sever I stumbled upon the same issue. I fixed it and initiated a pull request.  
I hope @lprhodes will have the time to review and merge it soon.

**Comment by willhains** [comment]
@KaloNikolov Where is the file, so I can edit it locally?

**Comment by tonyshare1** [comment]
same as this.
https://github.com/lprhodes/broadlinkjs-rm/pull/10
to fix this, you could modify the nodejs code in your pi/computer..

**Comment by willhains** [comment]
Duplicate of #12
