### ISSUE TITLE
Rm Pro does not recognize Rf signal of Tc2 Switchs.

### ISSUE THREAD

**Issue by Julianex22** [lprhodes/broadlinkjs-rm#13]
Hello lprhodes, Rm Pro does not record the signal of tc2 Switches, they are wall switch which link to Rm Pro through Rf signal 433 Mhz.
Please give me some help about.

Thanks for your willing.

**Comment by adityachopra8** [comment]
same problem. added code from rm plugin but it does not go to the rm pro 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lprhodes** [comment]
@Julianex22 are you bringing the RM Pro right up to the switches? They need to be pretty close.
