### ISSUE TITLE
RM Mini 3 support

### ISSUE THREAD

**Issue by fbacker** [lprhodes/broadlinkjs-rm#14]
There's no support for Mini 3.
Also I see there's 2 pull requests to enable this. Both using same id.

So please pick one, merge the pull and make a new npm release.

Cheers

**Comment by fbacker** [comment]
I'm currently running https://github.com/KaloNikolov/broadlinkjs-rm#patch-1 (pull request) until this is merged and npm submited.

**Comment by kiwi-cam** [comment]
Hi @fbacker . Are you seeing Unhandled Command: 114 when using an RM Mini 3?  I am, and others are too: https://github.com/lprhodes/homebridge-broadlink-rm/issues/475

Any idea what the command 0x72/114 is? Can we just ignore this device?

**Comment by fbacker** [comment]
@kiwi-cam sorry, I don't have a RM Mini 3 so can't test. After the fix I havn't had complaints on my project. But not gotten any feedback if it works either :/

**Comment by kiwi-cam** [comment]
All good. There's been a bit of talk about it on another project and the RM Mini 3 looks like it might be the common detail. Just wondered if you might've had some thoughts on it, or the what the command was based on your work here.

I'll keep poking around and see what I can find :-)

Thanks for getting back to me.
