### ISSUE TITLE
Multi network interfaces support

### ISSUE THREAD

**Issue by paolotremadio** [lprhodes/broadlinkjs-rm#7]
Hi,

I saw you just added the support for multiple ip addresses but it still does not support multiple network interfaces.

My setup: I have a Mac running homebridge with two network adapters; the first one is connected to the router for full internet connectivity. The second interface is a wifi router, disconnected from the internet, with just some non-homekit devices onto it (including my broadlink).

Any chances to support multiple network adapters?

**Comment by lprhodes** [comment]
Hi @paolotremadio

I've fixed that in the latest version
