### ISSUE TITLE
Question: How can I use this module?

### ISSUE THREAD

**Issue by Komagain** [lprhodes/broadlinkjs-rm#8]
hello,
It is a question, not an issue.
Can you explain how can I use this module?

- Do I need an IOS thing? or can I use from a PC?
I already have installed homebridge

Thanks

**Comment by Digicrat** [comment]
This project is just a library, you will need to build upon it or use an app/lib dependent on it to make use of it.  I just came across this module myself as a dependency of https://github.com/TheAslera/broadlink-rm-http

I don't know much about HomeBridge, but you probably want https://www.npmjs.com/package/homebridge-broadlink-rm
